### ISSUE TITLE
Resilient

### ISSUE THREAD

**Issue by bnayae** [outsidenote/eventualize#4]
When the Aggregator fails because of optimistic concurrency, it can re-fetch the current state and try again via [Polly](https://github.com/App-vNext/Polly).

**Comment by outsidenote** [comment]
There could be multiple strategies to deal with an OCC error:

1. The staleness of our state **does not prohibit** storing the events - in that case we might want to set a flag of `ignoreOCC` in `SaveAsync()` and store the events with the correct sequence ids.
2. The staleness of our state **prohibits** storing the events - in that case we should let the users decide what do to. A retry might be one decision (but in the case, maybe the previous case is mot suitable), but they could also decide to cancel the operation because the new state made the current store operation invalid.

Doe that make sense?
