### ISSUE TITLE
NJsonSchema, do we need it?

### ISSUE THREAD

**Issue by bnayae** [outsidenote/eventualize#6]
If we do need it we have to setup an abstraction

**Comment by bnaya-payoneer** [comment]
```cs
using Generator.Equals;

namespace Eventualize.Core;

// TODO: Json data -> JsonElement if needed at all
[Equatable]
public partial record EventEntity (
                //string EventType,
                DateTime CapturedAt, 
                string CapturedBy, 
                DateTime? StoredAt)
{ 
}

[Equatable]
public partial record EventEntity<T> (
                //string EventType,
                DateTime CapturedAt, 
                string CapturedBy, 
                T JsonData, 
                DateTime? StoredAt): EventEntity(CapturedAt, CapturedBy, StoredAt)
{ 
}
```

**Comment by outsidenote** [comment]
I agree, we don't need to use JSONSchema in this case.

So if I understand correctly, of the event's payload will happen in the Repository, just before sending it to the `SaveAsync()` of `IStoreAdapter`?
In that case, do we need to declare on a serialized event interface to be sent there?
```cs
[Equatable]
public partial record SearializedEventEntity (
                string EventType,
                DateTime CapturedAt, 
                string CapturedBy, 
                string JsonPayload,
                DateTime? StoredAt)
{
}
```

BTW,  I'm fore adopting your terminology of `EventEntity.Payload` instead of `EventEntity.JsonData`.

**Comment by outsidenote** [comment]
Another question (I separated the thoughts into different posts...):
If now we have `EventEntity<T>` with generics.
How do we represent a `List` of such events with different generic types?
